export const users = [
  {
    avatar: "https://img.icons8.com/?size=512&id=Rke83hCOnYV0&format=png",
    name: "Ivan",
    date: "12.50",
    text: "UGIGBUBKUNKNJHNJHnjhnjhn",
    number: "4",
  },
  {
    avatar: "https://img.icons8.com/?size=512&id=Rke83hCOnYV0&format=png",
    name: "Vasia",
    date: "11.50",
    text: "UGIGBUBKUNKNJHNJHnjhnjhn",
    number: "1",
  },
  {
    avatar: "https://img.icons8.com/?size=512&id=Rke83hCOnYV0&format=png",
    name: "Ivan21",
    date: "10.50",
    text: "UGIGBUBKUNKNJHNJHnjhnjhn",
    number: "4",
  },
  {
    avatar: "https://img.icons8.com/?size=512&id=Rke83hCOnYV0&format=png",
    name: "VasiaReper",
    date: "9.50",
    text: "UGIGBUBKUNKNJHNJHnjhnjhn",
    number: "1",
  },
  {
    avatar: "https://img.icons8.com/?size=512&id=Rke83hCOnYV0&format=png",
    name: "KoliaBog",
    date: "10 Мая 2023",
    text: "cxx.fnfgdfgsdgserdf fgdfghjfghfhgfh nvhffhgdxh grgwe g,jnfdkgjndf jgnd fjgndfjknkfjdgnjdsf vdslfmvdlfkmvd;fldlf,gfg,blfgh,lgh,gb",
    number: "2",
  },
  {
    avatar: "https://img.icons8.com/?size=512&id=Rke83hCOnYV0&format=png",
    name: "12133434",
    date: "7 Мая 2023",
    text: "cxx.fnfgdfgsdgserdf fgdfghjfghfhgfh nvhffhgdxh grgwe g,jnfdkgjndf jgnd fjgndfjknkfjdgnjdsf vdslfmvdlfkmvd;fldlf,gfg,blfgh,lgh,gb",
    number: "3",
  },
  {
    avatar: "https://img.icons8.com/?size=512&id=Rke83hCOnYV0&format=png",
    name: "Bib312123",
    date: "5 Мая 2023",
    text: "cxx.fnfgdfgsdgserdf fgdfghjfghfhgfh nvhffhgdxh grgwe g,jnfdkgjndf jgnd fjgndfjknkfjdgnjdsf vdslfmvdlfkmvd;fldlf,gfg,blfgh,lgh,gb",
    number: "13",
  },
];
